### PR TITLE
Remove dump jpeg stream

### LINKED ISSUE #32: DUMP_JPEG_STREAM debug code should be removed from src/decenc_openjpeg.c
In PR #3 I forgot to remove debug code in src/decenc_openjpeg.c that dumps jpeg stream to a file. It should be removed.

### PR DESCRIPTION
**Pull request by DusanJovic-NOAA**
Remove DUMP_JPEG_STREAM debug code from src/decenc_openjpeg.c.

Fixes #32.

### CODE REVIEW

**Comment by edwardhartnett** [comment]
Is this PR still active? Should it be merged or closed?

**Comment by DusanJovic-NOAA** [comment]
> Is this PR still active? Should it be merged or closed?

This PR is still active. I think it should be merged.

**Comment by edwardhartnett** [comment]
Can you add a test please?

**Comment by DusanJovic-NOAA** [comment]
> Can you add a test please?

This PR does not add any new feature that requires adding new test(s). Whatever testing procedure is used for the previous PRs can be used for this one.

**Comment by edwardhartnett** [comment]
Tests are required. Why was this PR closed?

**Pull request closed without merging**
