### PR TITLE
Add BUILD_SHARED_LIBS option

### LINKED ISSUE #253: Add option to build g2c with shared libraries
This library defaults to static, and I don't think there's any good reason for that. When building Grads using Spack, I had to compile g2c with `-fPIC` which could resolved by just compiling shared libraries. Also `grib2io` uses g2c from Python and uses a shared library to do this.

### PR DESCRIPTION
**Pull request by kgerheiser**
And default to build shared libraries. I don't think there's any good reason to default to static libraries.

Fix #253

### CODE REVIEW

**Comment by kgerheiser** [comment]
The Unix builds are now passing, but the Windows tests fail. I don't know much about Windows dynamic libraries, should I just add `-DBUILD_SHARED_LIBS=OFF` in Windows?

**Comment by edwardhartnett** [comment]
The windows CI was added by @DusanJovic-NOAA .

I think adding -DBUILD_SHARED_LIBS=OFF in Windows would be fine for now.

**Comment by kgerheiser** [comment]
That seems to have resolved the Windows issue

**Review by DusanJovic-NOAA — APPROVED** [review]

**Comment by kgerheiser** [comment]
Could I get a review @edwardhartnett

**Review by edwardhartnett — APPROVED** [review]

**Pull request merged**
