### PR TITLE
CI updates

### LINKED ISSUE #497: Update CI
Update the CI to use EMC GitHub Actions, recent versions for checkout/cache/etc. actions, etc.

### PR DESCRIPTION
**Pull request by AlexanderRichert-NOAA**
Various CI updates, added EMC Actions, etc.

Fixes #497

### CODE REVIEW

**Comment by edwardhartnett** [comment]
Should I merge this?

**Comment by AlexanderRichert-NOAA** [comment]
Yes this is good to go.

**Comment by edwardhartnett** [comment]
Seems like none of these workflows are working...

**Comment by edwardhartnett** [comment]
Can you add an issue for this work?

**Comment by AlexanderRichert-NOAA** [comment]
Looks like they were waiting on a conflict to be resolved (now resolved).

**Review by edwardhartnett — APPROVED** [review]

**Pull request merged**
