### PR TITLE
trying to turn on code analysis

### LINKED ISSUE #395: take advantage of new code scanning feature of GitHub actions
See https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/about-code-scanning

Let's give it a try...

### PR DESCRIPTION
**Pull request by edwardhartnett**
Fixes #395 

I would have liked to add this to the develop workflow, but it conflicts with the address santizer.

So I put the code analysis in the Intel build, since there is only one instance of the Intel build in this repo's CO.

### CODE REVIEW

**Comment by edwardhartnett** [comment]
The code scanner finds some problems I will address in a future PR. We will ignore its failure for now, but note that all the required CI workflows are passing.

This PR can be merged.

**Review by AlexanderRichert-NOAA — APPROVED** [review]
This is pretty cool. Is this something you intend to add to the other libs? And in the future, will the expectation be that the test should pass?

**Comment by edwardhartnett** [comment]
@AlexanderRichert-NOAA yes, I intend to add it everywhere across NCEPLIBS. I have not yet seen what it can do for Fortran however.

Also I intend to fix all scan errors and the require that the code scan pass for future PRs. But it might take me a few PRs to get there. ;-)

I used this code scanner in a recent refactor of my netcdf-c code. I found it useful for tightening up and cleaning up the code. Just like compiler warnings, it takes some work to get down to zero, but then the tool lurks in the background, ready to pounce on the slightest deviation from best practice in new code.

**Comment by edwardhartnett** [comment]
OK, no doubt it's childish, but the little red 'x' next to this PR is like fingernails on a chalkboard to me...

Let me see if I can fix some.

**Comment by edwardhartnett** [comment]
@AlexanderRichert-NOAA well it turns out that this code analysis tool does not support Fortran at all: https://codeql.github.com/docs/codeql-overview/supported-languages-and-frameworks/

From my netCDF and other code maintenance experience, I know that C is a lot easier to maintain than Fortran. This code scanner is just a small example of why.

**Pull request merged**
