### PR TITLE
Removed some unneeded defined types: g2float and g2int32u

### LINKED ISSUE #261: change g2float to just float
No need to define our own types when there already is one that we can use.

### PR DESCRIPTION
**Pull request by edwardhartnett**
Fixes #261

### CODE REVIEW

**Comment by edwardhartnett** [comment]
@Hang-Lei-NOAA please review.

**Review by Hang-Lei-NOAA — APPROVED** [review]
I strongly support to replace these specific defined types.

**Comment by DusanJovic-NOAA** [comment]
Each application that uses `g2float` to declare arrays passed to some (public) g2 functions (like g2_addfield) is now broken. Was this necessary?

**Comment by edwardhartnett** [comment]
Why do we need to rename an already existing type in C?

We can never change from float to something else, because that would break everything. So why give it a new name? And why in the world would other applications use that name?

If we need to re-add the typedef in order to ensure backward compatibility we can do that. But we will still use "float" to mean float in our code, because that is simpler. 

How many applications are we talking about? My understanding was that most NOAA applications use the Fortran library.

**Comment by DusanJovic-NOAA** [comment]
> Why do we need to rename an already existing type in C?
> 
I guess the reason is (or at least was) so that the library can be compiled with different g2float type.
 
> We can never change from float to something else, because that would break everything. So why give it a new name? And why in the world would other applications use that name?
> 
We can never change float to something else, but we can change g2float to something else, double for example. For the same reason we provide multiple versions of fortran g2 library.
 
> If we need to re-add the typedef in order to ensure backward compatibility we can do that. But we will still use "float" to mean float in our code, because that is simpler.
> 
Of course float should be used to mean float, but that that's not the case here. Well, it is at this moment since there's no build option to change g2float to something else. Are you going to change g2int to int?

> How many applications are we talking about? My understanding was that most NOAA applications use the Fortran library.

I do not know. But I'm not talking just about NOAA applications. This library is distributed in many popular Linux distributions, for example

debian: https://sources.debian.org/src/g2clib
ubuntu: https://packages.ubuntu.com/jammy/libgrib2c-dev
fedora: https://src.fedoraproject.org/rpms/g2clib

**Comment by edwardhartnett** [comment]
The C library will handle both doubles and floats without being recompiled. The types of the parameters for each function will never change. 

In terms of C programmers outside NOAA, I very much doubt that anyone is thinking to use g2float as a way for the type to change at compile time. No one else does that, because it's a terrible way to handle floats and doubles.

Here's the netCDF API for getting data as floats and doubles:

```
EXTERNL int
nc_get_vara_float(int ncid, int varid,
        const size_t *startp, const size_t *countp, float *ip);

EXTERNL int
nc_get_vara_double(int ncid, int varid, const size_t *startp,
                   const size_t *countp, double *ip);

```

There is one function to return float, and another to return double. Note that both functions co-exist. A user can write code that handles some variables as float and some as double, all within the same program (and this is common). That would not be possible if we used one defined type and changed it with compile flags or a pre-processor symbol.

And this is how NCEPLIBS-g2c will handle floats and doubles:

```
void pngpack(float *fld, g2int width, g2int height, g2int *idrstmpl,
             unsigned char *cpack, g2int *lcpack);
g2int pngunpack(unsigned char *cpack, g2int len, g2int *idrstmpl, g2int ndpts,
                float *fld);
void pngpackd(double *fld, g2int width, g2int height, g2int *idrstmpl,
             unsigned char *cpack, g2int *lcpack);
g2int pngunpackd(unsigned char *cpack, g2int len, g2int *idrstmpl, g2int ndpts,
                double *fld);

```

Note that there is now a double version of pngpack()/pngunpack(). Both sets of functions are available in the library, so users can mix float and double code as they wish.

WRT g2int: we will never, ever compile the g2c library with a different size int. That would break all calling programs, unless they had consistently and correctly used g2int everywhere, and this is unlikely. It's unreasonable for us to introduce a new set of types that g2c users have to use throughout their code, instead of standard types. It's also unnecessary.

NCEPLIBS-g2c will handle types the same way other Unix C libraries handles types. That what users expect, that's what works well for Fortran interoperability, and that's what's simplest and easiest to maintain.

**Comment by DusanJovic-NOAA** [comment]
Many programs use g2float/g2int to declare g2c function parameters. For example:

gdal: https://github.com/OSGeo/gdal/blob/9f269de726dd052e782167d3a602036492b8d33a/frmts/grib/gribdataset.cpp#L554
MET: https://github.com/dtcenter/MET/blob/0cbdd5f97437990e1ab4642d85de277a99242792/met/src/libcode/vx_data2d_grib2/data2d_grib2.h#L104
grads: https://github.com/j-m-adams/GrADS/blob/067f2e83fb5ede55920472714166384fb212a5aa/src/gagmap.c#L67

All of these programs/libraries are widely used both inside and outside NOAA.

I'm not going to argue whether the original decision to typedef C builtin types was good or bad decision and use them to define public function signatures, but it is what it is and people rely on these names.

Removing g2float and/or g2int typedefs is public API breaking change.

**Comment by edwardhartnett** [comment]
I will re-add the typedef for backward compatibility.

We will use float/double properly moving forward, but this legacy typedef can remain.

**Pull request merged**
