### PR TITLE
clean up g2_free.c, g2_addlocal.c, g2_addgrid.c documentation and comments

### PR DESCRIPTION
**Pull request by edwardhartnett**
Part of #47 
Part of #54 

clean up g2_free.c, g2_addlocal.c documentation and comments

### CODE REVIEW

**Review by Hang-Lei-NOAA — APPROVED** [review]

**Comment by DusanJovic-NOAA** [comment]
Please use squashed merge when merging pull request.

**Comment by edwardhartnett** [comment]
Not a fan of squashed merges. Can you justify this request?

The reason I'm not a fan is that in NCEPLIBS we frequently see very many large PRs with many changes. If we had smaller PRs, then squashed merges would make more sense.

What is the benefit of squashed merges?

**Comment by DusanJovic-NOAA** [comment]
> Not a fan of squashed merges. Can you justify this request?
> 
> The reason I'm not a fan is that in NCEPLIBS we frequently see very many large PRs with many changes. If we had smaller PRs, then squashed merges would make more sense.
> 
> What is the benefit of squashed merges?

To avoid having commit history like this:
```
61c1074 more code cleanup
3e87907 more code cleanup
1da63c4 more code cleanup
3b13656 more cleanup
651b7d0 more cleanup
4aa9250 cleaned up g2_free.c
67da1e8 cleaned up g2_free.c
9f0e786 fixed compack docs
6e69489 removed inadvertant changes to cmplxpack.c
aabdb67 cleaned up g2_create
575b40d fixing comments
7d15594 fix doxygen
94c82b4 fixed cmplxpack.c
3f3096b changes
42ac6c3 changes
6a9dc45 changes
```
Pretty soon 99% of commits will be "changes" or "more cleanup", or "more fixes". It will become impossible to spot commits that introduce actual code changes.

All those intermediate commits you make are completely irrelevant for overall project history. No one should care about dozens of hundreds of commits made in each PR.

**Comment by edwardhartnett** [comment]
Yet on the netcd-c project, we sometimes use all these commits to find the exact one that introduced a problem on some obscure platform that is not part of CI...

**Pull request merged**
