### PR TITLE
Support png bit depths 1, 2 and 4

### LINKED ISSUE #508: png support for 1, 2 or 4 bit depths?
Does g2c support png-encoded grib files with bit depths of  1, 2 or 4?

### PR DESCRIPTION
**Pull request by DusanJovic-NOAA**
Update png pack/unpack and encode/decode routines to support bit depths 1, 2 and 4. 

Fixes #508

### CODE REVIEW

**Comment by edwardhartnett** [comment]
I think you will get the missing test runs when you merge in the develp branch.

These look like good changes, and thanks a lot for the tests!

Let me know when this is ready to merge.

**Comment by DusanJovic-NOAA** [comment]
@webisu Do you want to test this branch with wgrib2 to see if png with 1, 2 and 4 bit depths works as expected?

**Comment by webisu** [comment]
Wgrib2 doesn't use g2c right now.

**Comment by edwardhartnett** [comment]
However, wgrib2 is about to start using g2c for compression.

@DusanJovic-NOAA I suggest that if this passes your tests we merge it and it can be tested further with wgrib2 later.

**Review by edwardhartnett — APPROVED** [review]

**Pull request merged**
