### PR TITLE
fix g2c_dec_png and make png grid size configurable

### LINKED ISSUE #557: Make max png size configurable to support large grids.
Decoding png returns the following error if the width / height is too large:
```shell
libpng warning: Image width exceeds user limit in IHDR
libpng error: Invalid IHDR data
``` 

The maximum size can be configured using:
```c
png_set_user_limits(png_ptr, PNG_WIDTH_MAX, PNG_HEIGHT_MAX);
```

### PR DESCRIPTION
**Pull request by AlysonStahl-NOAA**
Fixes #557 

This PR also contains some fixes to the g2c_dec_png() function. We want wgrib2 to work with g2c decoders and wgrib2 needs to support larger girds. I've tested these changes with wgrib2 and everything now works as expected.

### CODE REVIEW

**Comment by AlysonStahl-NOAA** [comment]
The spack check is failing for an unrelated reason (Issue #559). All checks are successful if I either remove the check at the end or set spack-ref to an older version.

**Comment by edwardhartnett** [comment]
We need a test of this change. That is, a test which would fail without this change, but passes with it.

**Comment by AlexanderRichert-NOAA** [comment]
Re: #559, can you try changing self.builder.build_directory to self.build_directory in package.py? It sounds like this just recently changed in Spack. If that doesn't work I can investigate further.

**Comment by AlysonStahl-NOAA** [comment]
> Re: #559, can you try changing self.builder.build_directory to self.build_directory in package.py? It sounds like this just recently changed in Spack. If that doesn't work I can investigate further.

Unfortunately I tried that already and that didn't work.

**Comment by AlysonStahl-NOAA** [comment]
> We need a test of this change. That is, a test which would fail without this change, but passes with it.

Done. Both changes have a test that breaks if I remove them.

**Review by edwardhartnett — APPROVED** [review]

**Pull request merged**
