### PR TITLE
Add support for using OpenJPEG library for JPEG2000 decoding/encoding

### PR DESCRIPTION
**Pull request by DusanJovic-NOAA**

### CODE REVIEW

**Comment by kgerheiser** [comment]
What's the benefit of OpenJPEG?

**Comment by DusanJovic-NOAA** [comment]
Jasper is not maintained anymore. May projects that need JPEG2000 compression already moved to OpenJPEG.

**Comment by kgerheiser** [comment]
Oh, so it replaces Jasper? That's good.

**Comment by DusanJovic-NOAA** [comment]
No. It's added as an alternative. Jasper is still used by default. See the top-level CMakeLists.txt:

https://github.com/DusanJovic-NOAA/NCEPLIBS-g2c/blob/954c38f6821caab23b9a8175300a54c1473a649f/CMakeLists.txt#L26

**Review by aerorahul — APPROVED** [review]

**Review by BoiVuong-NOAA — APPROVED** [review]

**Pull request merged**
